### ISSUE TITLE
Problem: EFGS Load balancer returns status code 200, when EFGS is not available

### ISSUE THREAD

**Issue by FWeissenseelTSystems** [eu-federation-gateway-service/efgs-federation-gateway#151] opened 2020-09-18 13:18 UTC
### Problem

- When a country backend sends a requests for upload/download/audit/callback to EFGS and EFGS confirms the request with an "ok", EFGS returns the status code 200.
- When EFGS is not available, the EFGS load balancer returns the webpage “https://sorry.ec.europa.eu/” (<title>Announcement: server inaccessibility - European Commission</title>) with the same status code 200.

**Problem**: When a country backend uploads keys and EFGS is not available, the country backend gets status code 200 and for that reason the backend thinks that the upload was working correct.

### Test to reproduce problem

1. Shut down EFGS
2. Country backend tries to upload/download/audit key batches.

**Expected**: 
- country backend gets status code not equal to 200.

**Actual**:
- EFGS load balancer returns "https://sorry.ec.europa.eu/" with status code 200
-  Country backend gets status code 200.

![EFGS_Loadbalancer_ErrorPage_With_statusCode_200](https://user-images.githubusercontent.com/69973980/93601425-7d097e80-f9c1-11ea-949d-ef70863a9b58.jpg)

**Comment by alstiefel** [comment] 2020-09-21 09:14
Communicated to DIGIT, update pending.

**Comment by alstiefel** [comment] 2020-09-25 09:00
Fixed as per mails

![image](https://user-images.githubusercontent.com/64828242/94248047-3914fd00-ff1e-11ea-905c-2eedf95b1bc1.png)

**Comment by chrloch** [comment] 2020-09-29 09:55
Solved on TEST:

HTTP/1.1 307 Temporary Redirect
Location: https://sorry.ec.europa.eu/efgs
Cache-Control: no-cache
Pragma: no-cache
Content-Type: text/html; charset=utf-8
Proxy-Connection: Keep-Alive
Connection: Keep-Alive
Content-Length: 768

HTTP/1.1 503 Service Unavailable
Date: Tue, 29 Sep 2020 09:53:31 GMT
Content-Length: 428
Content-Type: text/html; charset=iso-8859-1
Server: Europa
Proxy-Connection: Keep-Alive
Connection: Keep-Alive

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>503 Service Unavailable</title>
</head><body>
<h1>Service Unavailable</h1>
<p>The server is temporarily unable to service your
request due to maintenance downtime or capacity
problems. Please try again later.</p>
<p>Additionally, a 503 Service Unavailable
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>


Still open on ACC

**Comment by novoelgy** [comment] 2020-11-04 15:11
503 redirects were configured in ACC and PROD.   - Thu 01/10/2020 10:19 - confirmed by Digit colleagues

![image](https://user-images.githubusercontent.com/67410736/98128660-72933d80-1eb8-11eb-82a6-a654ccd69c47.png)

**Comment by joerg-oppermann-tsi** [comment] 2020-11-04 15:54
Fixed in Test, ACC, PRD

**Closed by joerg-oppermann-tsi** 2020-11-04 15:54 UTC
Labels: 3rd Prio - Low
